apiVersion: v1
kind: Service
metadata:
  name: {{ include "predixy.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "predixy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: tcp-predixy
  selector:
    {{- include "predixy.selectorLabels" . | nindent 4 }}
